PRAGMA foreign_keys = ON;

CREATE TABLE CLIENTE(
    CID INTEGER,
    NIF TEXT NOT NULL UNIQUE,
    NOME VARCHAR NOT NULL,
    N_TELEFONE TEXT CHECK(LENGTH(N_TELEFONE)=9),
    EMAIL VARCHAR,
    LOCALIDADE VARCHAR,
    MORADA VARCHAR,
    PRIMARY KEY(CID)
);

CREATE TABLE SERVIÇO(
    SID INTEGER,
    TIPO_SERVIÇO VARCHAR NOT NULL,
    PREÇO REAL NOT NULL,
    HORA_INICIO TIME,
    HORA_FIM TIME,
    PRIMARY KEY(SID)
);

CREATE TABLE EPOCA(
    EPID INTEGER,
    DATA_INICIO DATE,
    Data_FIM DATE CHECK (DATA_FIM > DATA_INICIO),
    PRIMARY KEY(EPID)
);

CREATE TABLE ESPAÇO(
    ESPID INTEGER,
    MORADA VARCHAR,
    AREA REAL NOT NULL,
    LOCALIDADE VARCHAR NOT NULL,
    PRIMARY KEY(ESPID)
);

CREATE TABLE EVENTO(
    EVID INTEGER,
    DATA_OCORRENCIA DATE NOT NULL,
    HORA_INICIO TIME,
    HORA_FIM TIME,
    N_CONVIDADOS INTEGER,
    TIPO VARCHAR,
    DESCRIÇAO VARCHAR,
    CID INTEGER NOT NULL,
    ESPID INTEGER NOT NULL,
    EPID INTEGER NOT NULL,
    UNIQUE(DATA_OCORRENCIA,ESPID),
    PRIMARY KEY(EVID),
    FOREIGN KEY(CID) REFERENCES CLIENTE(CID),
    FOREIGN KEY(ESPID) REFERENCES ESPAÇO(ESPID),
    FOREIGN KEY(EPID) REFERENCES EPOCA(EPID)
);

CREATE TABLE FUNCIONARIO(
    FUNCID INTEGER PRIMARY KEY,
    NIF TEXT UNIQUE,
    NOME VARCHAR NOT NULL,
    MORADA VARCHAR,
    DATA_NASCIMENTO DATE CHECK(DATA_NASCIMENTO < CURRENT_DATE),
    N_TELEFONE TEXT CHECK(LENGTH(N_TELEFONE)=9),
    SID INTEGER REFERENCES SERVIÇO(SID),
    FORNID INTEGER REFERENCES FORNECEDOR(FORNID)
);

CREATE TABLE FORNECEDOR(
    FORNID INTEGER PRIMARY KEY,
    NIF TEXT UNIQUE,
    NOME VARCHAR NOT NULL,
    MORADA VARCHAR,
    N_TELEFONE TEXT CHECK(LENGTH(N_TELEFONE)=9),
    EMAIL VARCHAR,
    MATERIAL VARCHAR
);

CREATE TABLE SERVIÇO_EVENTO(
    SID INTEGER,
    EVID INTEGER,
    PRIMARY KEY(SID, EVID),
    FOREIGN KEY(SID) REFERENCES SERVIÇO(SID),
    FOREIGN KEY(EVID) REFERENCES EVENTO(EVID)
);

CREATE TABLE TAXA_VARIAÇAO_PREÇO(
    SID INTEGER,
    EPID INTEGER,
    PERCENTAGEM_VARIAÇAO REAL NOT NULL,
    PRIMARY KEY(SID, EPID),
    FOREIGN KEY(SID) REFERENCES SERVIÇO(SID),
    FOREIGN KEY(EPID) REFERENCES EPOCA(EPID)
);

CREATE TABLE PAGAMENTO_CLIENTE(
    SID INTEGER,
    CID INTEGER,
    METODO VARCHAR NOT NULL,
    DATA_REGISTO DATE,
    PRAZO_LIQUIDAÇAO DATE NOT NULL,
    MONTANTE REAL NOT NULL,
    PRIMARY KEY(SID, CID),
    FOREIGN KEY(SID) REFERENCES SERVIÇO(SID),
    FOREIGN KEY(CID) REFERENCES CLIENTE(CID)
);

CREATE TABLE PAGAMENTO_FORNECEDOR(
    SID INTEGER,
    FORNID INTEGER,
    METODO VARCHAR NOT NULL,
    DATA_REGISTO DATE,
    MONTANTE REAL NOT NULL,
    PRIMARY KEY(SID, FORNID),
    FOREIGN KEY(SID) REFERENCES SERVIÇO(SID),
    FOREIGN KEY(FORNID) REFERENCES FORNECEDOR(FORNID)
);