PRAGMA foreign_keys = ON;

CREATE TABLE CLIENTE(
    CID NUMERIC(),
    NIF NUMERIC() NOTNULL,
    NOME VARCHAR() NOTNULL,
    N_TELEFONE NUMERIC() CHECK(000000000<=N_TELEFONE<=999999999) NOTNULL,
    EMAIL VARCHAR(),
    LOCALIDADE VARCHAR(),
    MORADA VARCHAR(),
    PRIMARY KEY(CID)
    UNIQUE(NIF)
);

CREATE TABLE SERVIÇO(
    SID NUMERIC(),
    TIPO_SERVIÇO VARCHAR() NOTNULL,
    PREÇO NUMERIC() NOTNULL,
    HORA_INICIO NUMERIC(),
    HORA_FIM NUMERIC(),
    PRIMARY KEY(CID)
);

CREATE TABLE EPOCA(
    EPID NUMERIC(),
    DATA_INICIO NUMERIC(),
    Data_Fim NUMERIC(),
    PRIMARY KEY(EPID)
);

CREATE TABLE ESPAÇO(
    ESPID NUMERIC(),
    MORADA VARCHAR(),
    AREA NUMERIC(),
    LOCALIDADE VARCHAR(),
    PRIMARY KEY(ESPID)
);

CREATE TABLE EVENTO(
    EVID NUMERIC(),
    DATA_OCORRENCIA NUMERIC() NOTNULL,
    HORA_INICIO NUMERIC(),
    HORA_FIM NUMERIC(),
    N_CONVIDADOS NUMERIC(),
    TIPO VARCHAR(),
    DESCRIÇAO VARCHAR(),
    CID NUMERIC(),
    ESPID NUMERIC() CHECK(UNIQUE(DATA_OCORRENCIA,ESPID)),
    EPID NUMERIC(),
    PRIMARY KEY(EVID)
    FOREIGN KEY(CID) REFERENCES CLIENT(CID)
    FOREIGN KEY(ESPID) REFERENCES ESPAÇO(ESPID)
    FOREIGN KEY(EPID) REFERENCES EPOCA(EPID)
);

CREATE TABLE FUNCIONARIO(
    FUNCID NUMERIC() PRIMARY KEY,
    NIF NUMERIC() UNIQUE,
    NOME VARCHAR() NOT NULL,
    MORADA VARCHAR(),
    DATA_NASCIMENTO DATE(),
    LOCALIDADE VARCHAR(),
    N_TELEFONE NUMERIC() CHECK(000000000 <= N_TELEFONE <= 999999999),
    SID NUMERIC() REFERENCES SERVIÇO(SID),
    FORNID NUMERIC() REFERENCES FORNECEDOR(FORNID)
);

CREATE TABLE FORNECEDOR(
    FORNID NUMERIC() PRIMARY KEY,
    NIF NUMERIC() UNIQUE,
    NOME VARCHAR() NOT NULL,
    MORADA VARCHAR(),
    N_TELEFONE NUMERIC() CHECK(000000000 <= N_TELEFONE <= 999999999),
    EMAIL VARCHAR(),
    MATERIAL VARCHAR()
);

CREATE TABLE SERVIÇO/EVENTO(
    SID NUMERIC(),
    EVID NUMERIC(),
    FOREIGN KEY(SID) REFERENCES SERVIÇO(SID),
    FOREIGN KEY(EVID) REFERENCES EVENTO(EVID),
    PRIMARY KEY(SID, EVID)
);

CREATE TABLE TAXA_VARIAÇAO_PREÇO(
    SID NUMERIC(),
    EPID NUMERIC(),
    FOREIGN KEY(SID) REFERENCES SERVIÇO(SID),
    FOREIGN KEY(EPID) REFERENCES EPOCA(EPID),
    TAXA NUMERIC(),
    PRIMARY KEY(SID, EPID)
);

CREATE TABLE PAGAMENTO_CLIENTE(
    SID NUMERIC(),
    CID NUMERIC(),
    FOREIGN KEY(SID) REFERENCES SERVIÇO(SID),
    FOREIGN KEY(CID) REFERENCES CLIENTE(CID),
    METODO VARCHAR() NOTNULL,
    DATA_REGISTO VARCHAR(),
    PRAZO_LIQUIDAÇAO VARCHAR(),
    MONTANTE NUMERIC() NOTNULL,
    PRIMARY KEY(SID, CID)
);

CREATE TABLE PAGAMENTO_FORNECEDOR(
    SID NUMERIC(),
    FORNID NUMERIC(),
    FOREIGN KEY(SID) REFERENCES SERVIÇO(SID),
    FOREIGN KEY(FORNID) REFERENCES FORNECEDOR(FORNID),
    METODO VARCHAR() NOTNULL,
    DATA_REGISTO VARCHAR(),
    MONTANTE NUMERIC() NOTNULL,
    PRIMARY KEY(SID, FORNID)
);